# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # codificacion de contrase√±as para registros y login
    encoders:
        BackendBundle\Entity\User:
             algorithm: bcrypt
             cost: 4

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_db_provider:
            entity:
               class: BackendBundle:User
               property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: logout
                target: /
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/(login|register|nick-test), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: [ROLE_USER, ROLE_ADMIN] }