private_message_index:
    path: /private-message
    defaults: { _controller: AppBundle:PrivateMessage:sendPrivateMessage }

private_message_sended:
    path: /private-message/sended
    defaults: { _controller: AppBundle:PrivateMessage:sended }