home_publications:
  path: /home
  defaults: { _controller: AppBundle:Publication:publications }

remove_publication:
  path: /publication/remove/{id}
  defaults: { _controller: AppBundle:Publication:removePublication, id: null }